const Netflixdata = [
    {
        id:1,
        sname: "DARK",
        imgsrc: "https://images-na.ssl-images-amazon.com/images/I/81oWDX24u%2BL._SL1200_.jpg",
        title: "Netflix Original Series",
        links: "https://www.netflix.com/in/title/80100172",
    },
    {
        id:2,
        sname: "BREAKING BAD",
        imgsrc: "https://th.bing.com/th/id/OIP.w2kFGhFOf3c9px521cmGowHaHa?w=181&h=181&c=7&o=5&dpr=1.25&pid=1.7",
        title: "Netflix Original Series",
        links: "https://www.netflix.com/in/Title/70143836",
    },
    {
        id:3,
        sname: "STRANGER THINGS",
        imgsrc: "https://wallpapercave.com/wp/wp5913975.jpg",
        title: "Netflix Original Series",
        links: "https://www.netflix.com/in/Title/80199393",
    },
    {
        id:4,
        sname: "MARVEL THE PUNISHER",
        imgsrc: "https://th.bing.com/th/id/OIP.cw-y_eBPqwVT1T-s43XieQHaEK?w=319&h=180&c=7&o=5&dpr=1.25&pid=1.7",
        title: "Netflix Original Series",
        links: "https://www.netflix.com/in/title/80117498",
    },
    {
        id:5,
        sname: "Game of Thrones",
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRrKGdBhaFG25lCiPlX29lgMq2NarNfQOABPw&usqp=CAU",
        title: "Netflix Original Series",
        links: "https://www.hbo.com/game-of-thrones",
    },
    {
        id:6,
        sname: "Black Mirror",
        imgsrc: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/black-mirror-font-1513096756.jpg?crop=1xw:1xh;center,top&resize=480:*",
        title: "Netflix Original Series",
        links: "https://www.netflix.com/in/title/70264888",
    },
    {
        id:7,
        sname: "Extracurricular",
        imgsrc: "https://fueledbystories.com/wp-content/uploads/2020/06/MV5BNGQxMDcyOTEtZWZkNi00NzgwLWEzNjQtZmFhMGY5ZGRlMTdiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
        title: "Netflix Original Series",
        links: "https://www.netflix.com/in/title/80990668",
    },
    {
        id:8,
        sname: "Mindhunter",
        imgsrc: "https://instrumentalfx.co/wp-content/uploads/2017/11/Mindhunter-theme-song.jpg",
        title: "Netflix Original Series",
        links: "https://www.netflix.com/in/title/80114855",
    },
    {
        id:9,
        sname: "The Witcher",
        imgsrc: "https://images.indianexpress.com/2019/12/the-witcher-netflix-1200.jpg",
        title: "Netflix Original Series",
        links: "https://www.netflix.com/in/title/80189685",
    },
    {
        id:10,
        sname: "Cobra Kai",
        imgsrc: "https://cdn.flickeringmyth.com/wp-content/uploads/2019/04/yto_cobrakai_vertical_27x40_132_v1_rgb.jpg",
        title: "YouTube Original Series",
        links: "https://www.netflix.com/in/title/81002370",
    },
    {
        id:11,
        sname: "The Hunting of Hill House",
        imgsrc: "https://m.media-amazon.com/images/M/MV5BMTU4NzA4MDEwNF5BMl5BanBnXkFtZTgwMTQxODYzNjM@._V1_.jpg",
        title: "Netflix Original Series",
        links: "https://www.netflix.com/in/title/80189221",
    },
]
export default Netflixdata;
